# Generated by Django 4.2.1 on 2023-05-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makale',
            old_name='guncellenme_tarihi',
            new_name='güncellenme_tarihi',
        ),
    ]
