# Generated by Django 4.2.1 on 2023-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_rename_guncellenme_tarihi_makale_güncellenme_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='yayımlanma_tarihi',
            field=models.DateField(),
        ),
    ]
